name: Release and Deploy to GitHub Pages

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
      - name: Install dependencies
        run: npm i
      - name: Build site
        run: NODE_ENV=production npm run build
      # in production builds, everything's compiled to a single file. remove extraneous assets
      - name: Trim site
        run: rm -r dist/{main.js,assets}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/index.html"
